### ISSUE TITLE
Error: g-io-error-quark: Timeout was reached (24)

### ISSUE THREAD

**Issue by llaumgui** [pulb/mailnag-goa-plugin#3]
Hi,

when I launch mailnag with this plugin, I have this message and no account found:

```
ERROR (2015-08-22 23:45:30): Caught an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Mailnag/common/utils.py", line 78, in try_call
    return f()
  File "/usr/lib/python2.7/site-packages/Mailnag/daemon/mailnagdaemon.py", line 177, in <lambda>
    try_call( lambda: f(self._accounts) )
  File "/usr/lib/python2.7/site-packages/Mailnag/plugins/goaplugin.py", line 56, in accounts_loaded_hook
    token = oauth2_based.call_get_access_token_sync(None)
Error: g-io-error-quark: Timeout was reached (24)
```

**Comment by auipga** [comment]
Is your keyring unlocked?

**Comment by llaumgui** [comment]
Hum, with my new portable it's OK...
